name: build

on:
  push:

jobs:
  windows:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: netmuxd.exe
            name: netmuxd-Windows-x86_64.zip
    steps:
      - name: Install dependencies for openssl
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows-static-md
      - name: Show Perl Version
        run: |
          perl -v
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
      # - name: Publish release artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: netmuxd-${{ matrix.platform.os_name }}
      #     path: target/${{ matrix.platform.target }}/release/netmuxd.exe
